# Generated by Django 2.0.6 on 2020-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('loaddata', models.DateField(auto_now_add=True, null=True)),
                ('showdata', models.DateField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='pic')),
                ('text', models.TextField()),
                ('resever', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
