# Generated by Django 2.0.6 on 2020-04-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pic1')),
                ('name', models.CharField(max_length=20, null=True)),
                ('setcion_number', models.CharField(max_length=20, null=True)),
                ('publish', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setcion_name', models.CharField(max_length=20, null=True)),
                ('video_size', models.CharField(max_length=20, null=True)),
                ('video_time', models.CharField(max_length=20, null=True)),
                ('video_address', models.CharField(max_length=20, null=True)),
                ('ready', models.CharField(max_length=20, null=True)),
                ('album_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='albumapp.Album')),
            ],
        ),
    ]
