# Generated by Django 2.0.6 on 2020-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setcion',
            name='video_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
